# Generated by Django 5.2.3 on 2025-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_photo_reported"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="reported_at",
            field=models.CharField(
                choices=[
                    ("law", "Нарушение законодательства РФ"),
                    ("ai", "Фото — генерация нейросети"),
                    ("rules", "Нарушение правил сайта"),
                ],
                default="law",
                max_length=10,
            ),
        ),
    ]
