# Generated by Django 5.2.3 on 2025-06-16 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0004_profile_email_alter_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
