# Generated by Django 5.2.3 on 2025-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_remove_profile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("attempts", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
