# Generated by Django 5.2.3 on 2025-06-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0006_loginattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="tags",
        ),
        migrations.AddField(
            model_name="photo",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="photos.tag",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
