# Generated by Django 5.2.3 on 2025-06-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0008_tagmergerequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagmergerequest",
            name="accepted",
        ),
        migrations.AddField(
            model_name="tagmergerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("accepted", "Принят"),
                    ("declined", "Отклонен"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
