# Generated by Django 5.2.3 on 2025-06-22 14:02

import django.core.validators
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0010_taggroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=photos.models.upload_to_dynamic),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.jpg",
                upload_to="avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
