# Generated by Django 5.2.3 on 2025-07-14 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0011_alter_photo_image_alter_profile_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["latitude", "longitude"], name="photos_phot_latitud_92201d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["date_taken"], name="photos_phot_date_ta_9d9df5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["tag"], name="photos_phot_tag_id_b44104_idx"),
        ),
    ]
