# Generated by Django 5.2.3 on 2025-07-21 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0012_photo_photos_phot_latitud_92201d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="photo",
            name="photos_phot_latitud_92201d_idx",
        ),
        migrations.RemoveIndex(
            model_name="photo",
            name="photos_phot_date_ta_9d9df5_idx",
        ),
        migrations.RemoveIndex(
            model_name="photo",
            name="photos_phot_tag_id_b44104_idx",
        ),
    ]
