# Generated by Django 3.2.16 on 2025-05-07 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='add_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='photos_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
